### PR TITLE
Icon addition

### PR DESCRIPTION
**Pull request by ardacebi**
Adds icon to the extension.

https://fontawesome.com/icons/chart-bar

### CODE REVIEW

**Comment by KyrneDev** [comment]
@ardacebi You'll have to wait for confirmation from one of the devs on this, but I'm almost positive this was done intentionally. If you look, because there is no icon, it doesn't show up on the extensions page. The devs probably don't want you to be able to disable the extension because it is so small, but also want to separate it out of core.

**Comment by ardacebi** [comment]
Just made it “in-case”. I saw it on dev-master so wanted to open a PR.

Thanks though.

**Comment by tobyzerner** [comment]
@CDK2020 interesting theory but I had just not gotten around to adding an icon in this case! 😂 

@ardacebi screenshot pls

**Comment by KyrneDev** [comment]
@ardacebi Just a quick note Flarum beta 8 uses Font Awesome 5 so `fas fa-` is required before the icon!

**Comment by ardacebi** [comment]
@CDK2020 https://github.com/flarum/flarum-ext-statistics/pull/6/commits/08043d7c43c9b9c7b0d821969211aa9691f6bb05 adds what you requested.

---

@tobscure I updated the backgroundColor and color with https://github.com/flarum/flarum-ext-statistics/pull/6/commits/9f3a62a4bdc74eaba2587d77e7119356f0261998 so it now looks better with the other bundled extension icons.

screenshot_2018-08-14 locflar

- Purple one with the chart icon is the new & updated one.
- The one with the same name and pure white background is the old one with no icon.

**Comment by franzliedke** [comment]
Thanks. I fixed the indentation for you. :wink:

**Pull request merged**
